### ISSUE TITLE
Disabling rules for specific parts of the schema

### ISSUE THREAD

**Issue by goldcaddy77** [cjoudrey/graphql-schema-linter#18]
There will be times where users want a rule 95% of the time, but want to disable it in certain situations like [eslint disable](http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments).

I guess the mechanism would need to be in a comment?

**Comment by cjoudrey** [comment]
Interesting. 🤔 

Do you have an example use case for this? I'd lean towards not implementing this unless someone absolutely needs it.

The GraphQL.js parser picks up comments as descriptions for the type that follows it.

Guessing we'd have to wrap all rules at runtime with a function that checks `getDescription(node)`.

**Comment by goldcaddy77** [comment]
The use case for this would be if somebody wanted all of their Enums sorted alphabetically, but in one instance it made a lot more sense to have them sorted in a more logical order.  I don't think this is critical early on... more rules are probably higher priority :)

**Comment by cjoudrey** [comment]
Makes sense. I'm sure some use case will come along in the future. For now I'd lean towards not adding it.

**Comment by emmenko** [comment]
I would also like to have this feature. Think about it as `eslint-disable/enable` comment syntax.

The use case I'm having at the moment is the same as @goldcaddy77 (enums sorted alphabetically).

I can image having something like:

```graphql
# /* graphql-schema-linter-disable enum-values-sorted-alphabetically */
enum Size {
  SMALL
  MEDIUM
  LARGE
  XLARGE
}
# /*  graphql-schema-linter-enable enum-values-sorted-alphabetically */
```

The `/**/`is just an example of having a special syntax to parse it.

Thanks a lot!

**Comment by cjoudrey** [comment]
@emmenko that's an interesting use case for an enum that shouldn't be sorted alphabetically. 🤔 

I find the syntax for enabling/disabling a bit verbose, but we can tweak that.

I'll take a stab at this shortly.

**Comment by cjoudrey** [comment]
@emmenko @goldcaddy77  I've spent the day toying on this and it looks like it won't be too difficult to add.

What are your thoughts on this syntax (inspired from [eslint](https://eslint.org/docs/user-guide/configuring.html#configuring-rules))?

```graphql
type Query { # lint-disable-line types-have-descriptions, another-rule
  # A viewer
  viewer: User!
}

# A user
type User {
  # lint-disable fields-have-descriptions

  email: String!
  username: String!

  # lint-enable fields-have-descriptions
}

# lint-disable enums-are-sorted-alphabetically
# Sizes
enum Size {
  SMALL
  MEDIUM
  LARGE
}

# lint-enable enums-are-sorted-alphabetically
```

Basically you have:

- `# lint-disable rule1, rule2, rule3, ...` 
- `# lint-enable rule1, rule2, rule3, ...`
- `# lint-disable-line rule1, rule2, rule3, ...`

An alternative to inline comments that I was thinking about is allowing people to disable rules for a specific GraphQL path in the configuration file. Something like this:

```json
{
  "reporting_overrides": {
    "Size": [
      { "disable": "enums-are-sorted-alphabetically" }
    ],
    "User.email": [
      { "disable": "fields-have-descriptions" }
    ],
  }
}
```

The downside is that it is no longer close to the schema definition.

I also wonder how frequent these exceptions will happen? It feels like these would be edge cases.

**Comment by cjoudrey** [comment]
Just thought of a potential issue with using comments within the schema definition to configure the linter.

When parsing the schema definition to build the schema, [GraphQL.js](https://github.com/graphql/graphql-js/blob/96a869af951e7b7216e7b79ccfcb170b779ad4e9/src/utilities/buildASTSchema.js#L468-L499) (and possibly other implementations) look before definitions and use any comments as the definition for that type.

For example:

```graphql
# A user
type User {
  # The e-mail of the user
  email: String!
}
```

The description of the `User` type will be `A user`. GraphQL.js will extract all contiguous comments before the definition and use that as the description.

The problem is that in examples like the one below, the `lint-disable` comment will be used as the `description` for the type `User`.

```graphql
# lint-disable some-rule
type User {
  email: String!
}
```

To solve this we would need to provide a function that lets people "clean" their schema before building their schema. I'm not :100: sure I like this.

**Comment by emmenko** [comment]
🤔 I see.
Yeah using comments doesn't seem to be the correct way to handle this.

You mention above using a configuration object and that it's not close to the schema.
How about having "ignore" (dot) files next the actual schema file instead? Something like `.gitignore` or `.eslintignore`. When globbing the files in the project you can check if there is such a "dot" file and use it for the related schema.
The file can simply contain e.g. a list of disabled rules, or even a more fine grained configuration (like to disable specific rules for specific types).

What do you think? Could this be a valid alternative?

**Comment by cjoudrey** [comment]
I like this idea. It almost sounds like supporting multiple configuration files where the configuration files in subdirectories take precedence over configuration files in parent directories.

This combined with specifying exceptions for a given _path_ could probably solve most issues. When I say _path_ I mean `Size`, `User.email`, `User.*`, etc..

**Comment by goldcaddy77** [comment]
Just getting caught up on this one. A few thoughts:

- Seems like having comments in the file is DOA because other tooling will read those comment she and display them (like Graphiql)
- Having a "cleaning" step seems like the linter would become too tangled with the DEV workflow.
- Not sure I like the idea of multiple ignore files as it makes the tool feel more heavyweight and many of the rules will span multiple files in the multiple schema files use case.

My vote would be to declare all of the rules and exceptions in the same spot, where you'd whitelist rules and blacklist individual exceptions based on @cjoudrey 's "path". We'd just need to figure out a way to make tagging schema with a rule seem obvious. Like ignoring enum capitalization on a particular enum: would we prefix the blacklist rule with 'Enum.<enum_name'> and then the rules engine would know to look at that format?

**Comment by cjoudrey** [comment]
I completely missed this comment of yours @goldcaddy77.

> Like ignoring enum capitalization on a particular enum: would we prefix the blacklist rule with 'Enum.<enum_name'> and then the rules engine would know to look at that format?

I was thinking we could follow the same way GraphQL builds the `path` argument in `errors`.

```graphql
type Query {
  a: String
}
```

The path to the field `a` would be `Query.a`.

```graphql
enum Status {
  DRAFT
  PUBLISHED
  HIDDEN
}
```

The path to the field `Status` would simply be `Status`. The path to the enum value `DRAFT` would be `Status.DRAFT`.

We could then allow overrides by doing:

```json
{
  "reporting_overrides": {
    "Status.DRAFT": ["disable enum-values-have-descriptions", "enable enum-values-all-caps"]
  }
}
```

I'm not :100: sure if this is user friendly though. 🤔

**Comment by cjoudrey** [comment]
Just circling back to this, now that descriptions are defined using strings, the concerns I had in https://github.com/cjoudrey/graphql-schema-linter/issues/18#issuecomment-326061500 are no longer an issue.

I'd be happy to support disabling rules using an inline comment like eslint supports.

**Comment by steezeburger** [comment]
@cjoudrey This would be great to have as I'd like to ensure my lint tests pass in my CI and we have some enums like:

```
# Days of the week
enum DayOfWeek {
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
  SUNDAY
}
```

**Comment by cjoudrey** [comment]
That’s a good use case @steezeburger. I’ll take a stab at this later this week. 😀

**Comment by nicosampler** [comment]
Hi @cjoudrey any progress in this?

**Comment by cjoudrey** [comment]
Hey @nicosampler, thanks for the reminder! 😄

Now that type descriptions and comments are distinguishable, I'll take another look at implementing this using inline comments (i.e. `# lint-disable enums-are-sorted-alphabetically`) as described in https://github.com/cjoudrey/graphql-schema-linter/issues/18#issuecomment-325818349.

**Comment by decrn** [comment]
I stitch schemas together using [`merge-graphql-schemas`](https://github.com/okgrow/merge-graphql-schemas)

I have defined a base `schema.graphql` file, that has a `Query`, `Mutation` and `Subscription` type. Other schemas can then extend these existing types.

I would like to exclude this `schema.graphql` file, because it specifically has a unused/undocumented resolver for each of these types.

It looks something like this: 
```gql
type Query {
    _: Boolean
}

type Mutation {
    _: Boolean
}

type Subscription {
    _: Boolean
}
```

**Comment by morris** [comment]
I'm using directives for this right now, but it naturally only works in my custom rules. For example, we have a rule that says list items should not be null, and can be overriden like this:

```graphql
type Foo {
  list: [Bar] @lint(disable: ["list-items-not-null"])
}
```

I use this simple helper in my custom rules:

```js
function isDisabled(node, rule) {
  const directives = node.directives || [];
  const directive = directives.find(it => it.name.value === 'lint') || { arguments: [] };
  const disabledRules = directive.arguments.find(it => it.name.value === 'disable') || { value: { values: [] } };

  return !!disabledRules.value.values.find(it => it.value === rule);
}
```

What do you think?

**Comment by nicosampler** [comment]
Hi @morris, how it will work if you need to disable an entire block?

**Comment by morris** [comment]
Actually, I just figured out a way to do it generally. Use this custom rule (must be the first rule in the ruleset):

```js
module.exports = { LintDirective };

function LintDirective(context) {
  const disabledStack = [[]];

  const originalReportError = context.reportError;
  context.reportError = function(err) {
    if (disabledStack[disabledStack.length - 1].indexOf(err.ruleName) === -1) {
      return originalReportError.apply(this, arguments);
    }
  };

  return {
    enter(node) {
      const directives = node.directives || [];
      const lint = directives.find(it => it.name.value === 'lint') || { arguments: [] };
      const disable = lint.arguments.find(it => it.name.value === 'disable') || { value: { values: [] } };
      const enable = lint.arguments.find(it => it.name.value === 'enable') || { value: { values: [] } };
      const current = disabledStack[disabledStack.length - 1];
      const next = new Set(current.concat(disable.value.values.map(it => it.value)));
      for (const rule of enable.value.values) {
        next.delete(rule);
      }
      disabledStack.push(Array.from(next));
    },
    leave() {
      disabledStack.pop();
    }
  };
}
```

Then add the lint directive to your schema:

```graphql
directive @lint(disable: [String!] = [] enable: [String!] = []) on
  QUERY |
  MUTATION |
  SUBSCRIPTION |
  FIELD |
  FRAGMENT_DEFINITION |
  FRAGMENT_SPREAD |
  INLINE_FRAGMENT |
  SCHEMA |
  SCALAR |
  OBJECT |
  FIELD_DEFINITION |
  ARGUMENT_DEFINITION |
  INTERFACE |
  UNION |
  ENUM |
  ENUM_VALUE |
  INPUT_OBJECT |
  INPUT_FIELD_DEFINITION
```

@nicosampler this method makes nodes in the AST inherit the disabled/enabled rules from the parent, however since there's no namespace or other "grouping" node in GraphQL ASTs, this will only work for types. For example:

```graphql
type Foo @lint(disable: ["fields-are-camel-cased"]) {
  NOT_CAMEL_CASED: String
  _id: String
}
```

as opposed to:

```graphql
type Foo {
  NOT_CAMEL_CASED: String @lint(disable: ["fields-are-camel-cased"])
  _id: String @lint(disable: ["fields-are-camel-cased"])
}
```

Would be nice to have this out of the box, as the above relies on some internals (e.g. ruleName property).

**Comment by morris** [comment]
@cjoudrey if you think this is a viable approach i'd be happy to provide a PR (or if you just adopt the method, naturally).

**Comment by decrn** [comment]
@morris I like your approach but feel like directives would clog up the schema too much, especially when combining them with other directives (that do have an inherent impact on the schema definition)

It is the most unique solution out of all the ones suggested here though

**Comment by morris** [comment]
Thanks @decrn, I understand your point :) Haven't seen a schema yet where directives are used excessively, though. Also disabling linter rules should be the exception rather than the rule. I feel both should be at most like 3% of AST nodes, especially because the only built-in directive (for schemas) is `@deprecated`. Additionally, `@deprecated` does not have real impact besides documentation (in default implementations at least).

Another fun thing to think about: With a `@lint(disable: [String], reason: String)` directive, you could even add a rule to enforce adding a reason for disabling a rule... slightly meta, but displays how powerful using a directive for this kind of thing is.

For me, the main argument for directives is the standard; there's no custom syntax to be invented, and directives can be consumed by any toolset, especially since the GraphQL parser doesn't provide comment AST nodes.

**Comment by cjoudrey** [comment]
I hadn't considered that solution @morris. Thanks for sharing!

I kinda agree with @decrn. My big concern is that I feel like we'd be mixing two concerns.

While the GraphQL spec only defines `@deprecated`, there are a bunch of other directives that are made possible by 3rd party libraries (eg. authorization/permissions, validation) or even different GraphQL server providers (think AWS AppSync and their `@aws_subscribe` directive). In all of these cases, the directives have a direct impact on the behaviour of the schema.

In the case of `@lint`, it has nothing to do with how the schema is run, it's only there to define how the schema is linted.

I didn't think through the possibility of `@lint` enough to be sure, but I'm definitely leaning towards the comment style mentioned in https://github.com/cjoudrey/graphql-schema-linter/issues/18#issuecomment-325818349.

> especially since the GraphQL parser doesn't provide comment AST nodes.

That's definitely a real issue. The way I got around this was by iterating through the lexer tokens. Here's a quick WIP branch I had started which demonstrates that: https://github.com/cjoudrey/graphql-schema-linter/compare/master...inline-configuration

**Comment by morris** [comment]
In the meantime, we've published our rules, including the lint-directive, here: https://github.com/mobilcom-debitel/graphql-schema-linter-extras - maybe its helpful to tinker around with it to see it in action. We'll happily switch to a built-in method, as soon as there is one :)

**Comment by damonmiller** [comment]
I have another use case for wanting to disable certain linter rules in some cases.  We have a schema which was defined some time ago and did not follow best practices like using all uppercase for ENUM values.  Since implementing this linter, we have added all uppercase values and marked the older non-uppercase values as deprecated, however, the old values still fail the linter.  These must remain in our schema otherwise its a breaking change.

```
enum MyOrderBy {
  DATETIME_ASC
  DATETIME_DESC
  dateTime_ASC @deprecated(reason: "Use `DATETIME_ASC`.")
  dateTime_DESC @deprecated(reason: "Use `DATETIME_DESC`.")
}
```
Would be great to disable the 'enum-values-all-caps' rule for just those 2 deprecated values.

**Comment by hellogerard** [comment]
This is a bit of a deal breaker for me. We have a legacy schema in place. Running the linter against it generates errors. I can't fix these errors without breaking backwards compatibility. I can disable the rules, but we have so many errors, I end up disabling nearly every rule. If I had this feature, I could disable the existing errors, and keep a tidy schema going forward.

**Comment by mshwery** [comment]
Hey @cjoudrey ! Chiming in that I agree with your concerns about the directives approach, albeit a very interesting idea. I would love to see your idea of the comments take shape to ignore parts of the schema.

If there are major blockers to that, the overrides format would work in a pinch! Did you have a branch started somewhere I could help push along?

**Comment by cjoudrey** [comment]
@mshwery thanks for the feedback.

As I mentioned in https://github.com/cjoudrey/graphql-schema-linter/issues/18#issuecomment-488528184, I'm not really fond of the directive approach for the reasons outlined in that comment.

I'm open to PRs that would accept inline configurations via comments a-la ESLint.

As a starting point, we could add a way to disable/enable certain rules via:

```graphql
# lint-disable rule, ...
# lint-enable rule, ...
```

For multi-file schemas, these comments would only apply to the file they are written in.

For example:

```graphql
# a.graphql

# lint-disable-rule types-have-descriptions

type A {  ... }
```

```graphql
# b.graphql

type B { ... }
```

In the above example, `types-have-descriptions` would still be enabled in `b.graphql`.

When I looked into this 3 years ago, making this change was tricky because these inline configuration comments were intertwined with descriptions written as comments. As per the June 2018 spec, [descriptions should be written as string values](https://spec.graphql.org/June2018/#sec-Descriptions) so this makes the problem a bit simpler.

@mshwery if you'd like to help with adding this feature, I think https://github.com/cjoudrey/graphql-schema-linter/compare/master...inline-configuration could be a good starting point. The branch contains the necessary code to extract the inline configuration from the schema AST.

Thinking out loud here.

Once we have extracted the inline configuration, we can validate the schema with the default specified rules, then [right before outputting the errors](https://github.com/cjoudrey/graphql-schema-linter/blob/e21bcefe9d6cd68cdb9e12fe77433f3060bb9f8d/src/validator.js#L69), we could filter out the errors based on the inline configuration. This implies knowing for a given `file` and `line`, what `rules` were enabled.

Hope that helps!

**Comment by id-ilych** [comment]
If the schema is generated from the code (as it is with https://graphql-ruby.org/ for example) then it would be hard to set up those comments. In that case, having an exceptions list separated from the schema is not that bad.

**Comment by mshwery** [comment]
PR is up. Sorry took me awhile to find time for this! https://github.com/cjoudrey/graphql-schema-linter/pull/237

**Comment by cjoudrey** [comment]
> If the schema is generated from the code (as it is with https://graphql-ruby.org/ for example) then it would be hard to set up those comments. In that case, having an exceptions list separated from the schema is not that bad.

@id-ilych That's a fair point that I hadn't considered. Now that @mshwery added the foundation for filtering errors using inline configurations, I wouldn't be opposed to accepting a pull request that piggy backs off this for the case you outlined.

**Comment by id-ilych** [comment]
@cjoudrey Actually I built an ad-hoc solution based on @morris 's [idea](https://github.com/cjoudrey/graphql-schema-linter/issues/18#issuecomment-487588408). With `graphql-schema-linter.config.js` like that:
```js
module.exports = {
  rules: [
    'aaa-with-excludes',
    'defined-types-are-used',
    'deprecations-have-a-reason',
    'descriptions-are-capitalized',
    'enum-values-all-caps',
    'enum-values-sorted-alphabetically',
    'my-custom-rule1',
    'my-custom-rule2'
    // ...
  ],
  schemaPaths: ['path/to/schema.graphql'], // this file is generated from code
  customRulePaths: ['rules/*.js'],
  // This config is activated by aaa-with-excludes rule
  // excludes: {
  //   [rule]: [
  //     [Type],
  //     [Type.field],
  //     [Type.field.parameter],
  //   ],
  // }
  excludes: {
    'my-custom-rule1': [
      'Foo.bar',
      'Foo.buz'
    ],
    'my-custom-rule2': [
      'Blem'
    ],
  }
}
```

The rule itself could be seen [here](https://gist.github.com/id-ilych/abbd534863a170dd6ccdf39265af1ff4).

If you give me a hint on how to convert this to a proper solution that could be merged I could try to make a PR :)

PS: other hints about this code are welcome too as I am not that experienced with JS :)

**Comment by dustinsgoodman** [comment]
@id-ilych Your solution looks extremely similar to the one that I wrote for my application but I love how you put excludes list in the main config. I'd love to see your solution turned into a PR and would happily assist you with it but I think you're virtually there already given your gist + config setup.

**Comment by id-ilych** [comment]
@dustinsgoodman thanks :) Though I would like to get rid of the hacks:
* `Aaa`-prefix for ordering
* Hardcoded relative path to the config

Also, I would love to get some hints on
* Exclusion targets list. For now there are only three modes: `Type`, `Type.field` and `Type.field.parameter` - is it enough?
* This [unexpected situation handling](https://gist.github.com/id-ilych/abbd534863a170dd6ccdf39265af1ff4#file-aaa_with_excludes-js-L42-L50). It looks ugly. What are the best practices in the JS world? Just an exception with a short message relying on the debugger to see the context?

Anyway, I guess all of those things could be addressed as part of the PR lifecycle. I will create one this week.

**Comment by id-ilych** [comment]
My PR https://github.com/cjoudrey/graphql-schema-linter/pull/240.
